In [1]:
#Numpy DataTypes
#Strings:used to represent the text data,teh text data given under quote marks "ABDC"
#integer: used to represnt the interger numbers:eg:-1,-2,-3
#float:used  to represent the real numbers eg:1.2,42.42
#boolean:used to represent the True or False
#complex:1.0+2.0j

In [ ]:
/* I-integers
b-boolean 
u-unsigned
f-float
c-complex
m-timedelta
M-datetime
O-object
S-string
U-unicode string
V-Fixed chunk of memory for other type
*/

In [2]:
#checking the datatype of the array
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [3]:
import numpy as np
arr=np.array(["Kumar","Raju","Bogireddy"])
print(arr.dtype)

<U9


In [ ]:
#creating the arrays with a defined datatype

In [ ]:
we use the array function() to create the arrays ans takes an optional argument: dtype that allows 
you to define the excepted datatype of the array elements

In [4]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#for i ,u ,f,s and U we can define the size as well

In [6]:
import numpy as np
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# what if value cannot be converted
the it raises the valueError

In [7]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')


ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#error  

In [ ]:
#converting the data type from float to integer by using the i as parameter value

In [9]:
import numpy as np 
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [10]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [12]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)
      

[ True False  True]
bool


In [ ]:
# copy and view in the array 
copy is the copy of the existing the array
view is the view of the array

In [13]:
#Copy example
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

#changes do not effect

[42  2  3  4  5]
[1 2 3 4 5]


In [14]:
#view of the array
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=23
print(x)
print(arr)

#changes will effect


[23  2  3  4  5]
[23  2  3  4  5]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


copy returns none 
view returns the orginal array

None
[1 2 3 4 5]


In [ ]:
#shape of the array
represents the number of elements in the each dimension

In [ ]:
To get the shape we give the attribute called shape that returns the a tuple with
the each index having the no of the corresponding elements

In [16]:
import numpy as np
arr =np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)

(2, 5)
