In [ ]:
#Array indexing is the same as accesssing the element
#and by referring the index number
#starts with the 0 it means first elemnt has the index 0 and second elemnt has the index 1

In [2]:
#example 
import numpy as np
arr = np.array([1,2,3,4])
print(arr[3])
print(arr[2])
print(arr[0])

4
3
1


In [6]:
#adding the elemnts after getting from the index 
import numpy as np
arr = np.array([3,4,5,6,9])
print(arr)
print(arr[0])
print(arr[1]+arr[3])

[3 4 5 6 9]
3
10


In [8]:
#accessing the 2d-elemnts
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)
print(arr[0,1])

[[1 2 3 4 5]
 [6 7 8 9 0]]
2


In [10]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(arr)
print(arr[0,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 12 13]]]
5


In [12]:
##negative indexing
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr[1,-1])

[[1 2 3 4]
 [5 6 7 8]]
8


In [ ]:
##Numpy array slicing

In [ ]:
# it means taking elements from one index to another given index
#we slice [start:end]
#and also in [start:end:step]
#we dont pass index 0 , end element , step -1


In [2]:
#example
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr[0:5])

[1 2 3 4 5]


In [3]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr[2:3])

[3]


In [4]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr[:5])

[1 2 3 4 5]


In [ ]:
# negative slicing

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[-3:-1])

[3 4]


In [ ]:
#step of the slicing

In [8]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr[1:5:2])

[2 4]


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[::2])

[1 3 5]


In [11]:
#slicing 2-d arrays
import numpy as np 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [12]:
import numpy as np 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,3])

[4 9]


In [13]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
