In [ ]:
#Random Number 
random number does not mean  a different number every time 
random means something that can not be predicted logically


In [ ]:
pseudo Random and True Random


In [ ]:
generate a random number 


In [ ]:
#generate random number
numpy offers the random module to work with random number

In [3]:
from numpy import random
x = random.randint(100)
print(x)

16


In [ ]:
#for float values  givesin between 0 and 1

In [4]:
from numpy import random
x = random.rand()
print(x)

0.15899294315945867


In [ ]:
#randint we have to specify the size of the array

In [6]:
from numpy import random
x=random.randint(100,size=(5))
print(x)

[65 81 87  7 12]


In [7]:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

[[ 5  9  9 81 92]
 [35 49 22 56 52]
 [ 0 29 74  4 38]]


In [ ]:
#choice usd to generate a random value from the array

from numpy import random
x=random.choice([3,5,6,7,8])
print(x)

In [9]:
from numpy import random 
x=random.choice([3,5,6,7,8])
print(x)

3


In [11]:
#add size to specify the shape of the array
from numpy import random 
x=random.choice([3,4,5,6,9],size=(3,5))
print(x)

[[9 5 5 4 4]
 [4 3 5 5 5]
 [3 3 3 5 9]]
