In [ ]:
#Data Distribution
data distribution is a list of all possibe values and how often each value occurs
important while working in statistics and data science
random modulre offers methods that return randomly generated data distributions

In [ ]:
#Random distibution
a random distribution is a set of random numbers that follow a ceratin possibility  density 
function

In [ ]:
we can generate random number based on the defined probalilites using the choice()
method of the random module

In [ ]:
the choice() method allows us to specify the probability using the choice()
method of the random module

In [3]:
from numpy import random 
x=random.choice([3,4,5,6],p=[0.1,0.6,0.3,0.0],size=(100))
print(x)

[4 4 4 3 3 4 4 4 4 5 4 4 4 5 4 4 5 5 4 5 5 4 5 5 5 4 3 4 4 4 4 4 4 4 4 4 4
 4 4 3 4 4 3 5 4 5 5 4 4 5 4 4 3 4 4 4 5 4 5 4 4 5 4 4 4 4 4 3 5 4 4 5 4 4
 5 4 5 4 5 4 4 4 3 4 4 5 4 4 4 3 5 4 4 5 4 4 3 4 4 4]


In [ ]:
#sum of all probality is 1

In [4]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 7 5 5]
 [7 7 3 7 7]
 [7 7 3 3 5]]
